/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.util.ArrayList;
import java.util.List;
import modelos.*;
import restaurante.*;

/**
 *
 * @author davidmacar
 */
public class VCamarero extends javax.swing.JDialog {

    FachadaAplicacion fap;
    VAutenticacion vaut;
    
    public VCamarero(java.awt.Frame parent, boolean modal, FachadaAplicacion fap) {
        super(parent, modal);
        this.vaut = (VAutenticacion) parent;
        this.fap = fap;
        initComponents();
        this.txtError.setVisible(false);
        ModeloTablaPlatos mtp = new ModeloTablaPlatos();
        this.actualizarMesas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMenu = new javax.swing.JButton();
        btnCobrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listPlatos = new javax.swing.JList<String>();
        jScrollPane3 = new javax.swing.JScrollPane();
        listMesas = new javax.swing.JList<String>();
        jScrollPane4 = new javax.swing.JScrollPane();
        listBebidas = new javax.swing.JList<String>();
        txtError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMenu.setText("VER MENU");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });
        getContentPane().add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(666, 147, -1, 88));

        btnCobrar.setText("Cobrar");
        btnCobrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCobrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCobrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(666, 303, 100, 47));

        jLabel1.setText("Mesas");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 17, -1, -1));

        jLabel2.setText("Platos");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 17, -1, -1));

        jLabel3.setText("Bebidas");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(498, 17, -1, -1));

        listPlatos.setModel(new ModeloListaStrings());
        listPlatos.setToolTipText("");
        jScrollPane1.setViewportView(listPlatos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 48, 256, 310));

        listMesas.setModel(new ModeloListaStrings());
        listMesas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listMesasMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(listMesas);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 48, 130, 310));

        listBebidas.setModel(new ModeloListaStrings());
        jScrollPane4.setViewportView(listBebidas);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 48, 250, 310));

        txtError.setForeground(new java.awt.Color(255, 0, 0));
        txtError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtError.setText("<html>Selecciona una mesa primero</html>");
        txtError.setAutoscrolls(true);
        txtError.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(txtError, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 60, 120, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        if(this.listMesas.isSelectionEmpty()){
            this.txtError.setVisible(true);
            return;
        }
        Mesa mesa = fap.obtenerMesa(Integer.parseInt(this.listMesas.getSelectedValue()));
        for(Plato p : mesa.getPlatos()){
            p.setServicio(this.fap.obtenerServicioPlato(p));
        }
        for(Bebida b : mesa.getBebidas()){
            b.setServicio(this.fap.obtenerServicioBebida(b));
        }
        fap.vistaMenu(this, mesa);
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnCobrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCobrarActionPerformed
        if(this.listMesas.isSelectionEmpty()){
            this.txtError.setVisible(true);
            return;
        }
        Mesa mesa = fap.obtenerMesa(Integer.parseInt(this.listMesas.getSelectedValue()));
        fap.vistaCajero(this, mesa);
        
    }//GEN-LAST:event_btnCobrarActionPerformed

    private void listMesasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listMesasMouseClicked
        this.txtError.setVisible(false);
        this.actualizarPlatos();
        this.actualizarBebidas();
    }//GEN-LAST:event_listMesasMouseClicked
    
    public void actualizarMesas(){
        List<Mesa> mesas;
        mesas = fap.obtenerMesas();
        int a;
        List<String> strMesas = new ArrayList();
        for(Mesa mesa : mesas){
           strMesas.add(String.valueOf(mesa.getNum_mesa()));
        }
        
        ModeloListaStrings mls;
        mls = (ModeloListaStrings) this.listMesas.getModel();
        mls.setElementos(strMesas);
    }
    public void actualizarPlatos(){
        List<Plato> platos;
        platos = fap.obtenerPlatosMesa(Integer.parseInt(this.listMesas.getSelectedValue()));
        ArrayList<String> strPlatos = new ArrayList();
        for(Plato plato : platos){
            strPlatos.add(plato.getNombre());
        }
        ModeloListaStrings mls;
        mls = (ModeloListaStrings) this.listPlatos.getModel();
        mls.setElementos(strPlatos);
    }
    public void actualizarBebidas(){
        List<Bebida> bebidas;
        bebidas = fap.obtenerBebidasMesa(Integer.parseInt(this.listMesas.getSelectedValue()));
        ArrayList<String> strPlatos = new ArrayList();
        for(Bebida bebida : bebidas){
            strPlatos.add(bebida.getNombre());
        }
        ModeloListaStrings mls;
        mls = (ModeloListaStrings) this.listBebidas.getModel();
        mls.setElementos(strPlatos);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCobrar;
    private javax.swing.JButton btnMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JList<String> listBebidas;
    private javax.swing.JList<String> listMesas;
    private javax.swing.JList<String> listPlatos;
    private javax.swing.JLabel txtError;
    // End of variables declaration//GEN-END:variables
}
