/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.util.ArrayList;
import modelos.*;
import restaurante.Bebida;
import restaurante.FachadaAplicacion;
import restaurante.Mesa;
import restaurante.Plato;




/**
 *
 * @author davidmacar
 */
public class VMenu extends javax.swing.JDialog {

    FachadaAplicacion fap;
    VCamarero vcam;
    Mesa mesa;
    
    public VMenu(java.awt.Dialog parent, boolean modal,FachadaAplicacion fap, Mesa mesa) {
        super(parent,modal);
        this.vcam = (VCamarero) parent;
        this.fap = fap;
        this.mesa = mesa;
        initComponents();
        this.actualizarModelo();
    }
    private void actualizarModelo() {
        ModeloTablaBebidas mtb = (ModeloTablaBebidas) this.tablaBebidas.getModel();
        ModeloTablaPlatos mtp = (ModeloTablaPlatos) this.tablaPlatos.getModel();
        ModeloListaStrings mls = (ModeloListaStrings) this.listPedido.getModel();
        mtb.setFilas(fap.obtenerBebidas());
        mtp.setFilas(fap.obtenerPlatos());
        ArrayList<String> pedido = new ArrayList();
        for(Plato p : fap.obtenerPlatosMesa(this.mesa.getNum_mesa())){
            pedido.add(p.getNombre());
        }
        for(Bebida b : fap.obtenerBebidasMesa(this.mesa.getNum_mesa())){
            pedido.add(b.getNombre());
        }
        mls.setElementos(pedido);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAlimentos = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPlatos = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaBebidas = new javax.swing.JTable();
        btnBuscar = new javax.swing.JButton();
        btnInfo = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        btnAnadir = new javax.swing.JButton();
        btnConfirmar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        listPedido = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tablaPlatos.setModel(new ModeloTablaPlatos());
        jScrollPane1.setViewportView(tablaPlatos);

        panelAlimentos.addTab("Platos", jScrollPane1);

        tablaBebidas.setModel(new ModeloTablaBebidas());
        jScrollPane2.setViewportView(tablaBebidas);

        panelAlimentos.addTab("Bebidas", jScrollPane2);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnInfo.setText("Informacion");
        btnInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoActionPerformed(evt);
            }
        });

        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });

        btnAnadir.setText("Añadir");
        btnAnadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnadirActionPerformed(evt);
            }
        });

        btnConfirmar.setText("Confirmar");

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jLabel1.setText("Pedido mesa");

        listPedido.setModel(new ModeloListaStrings());
        jScrollPane4.setViewportView(listPedido);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnInfo)
                        .addGap(235, 235, 235)
                        .addComponent(btnAnadir, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(226, 226, 226))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(panelAlimentos, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(296, 296, 296)
                            .addComponent(btnBuscar)
                            .addGap(18, 18, 18)
                            .addComponent(txtBuscar))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(73, 73, 73)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnConfirmar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBuscar)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(6, 6, 6)
                        .addComponent(panelAlimentos, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnInfo)
                        .addComponent(btnAnadir))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnConfirmar)
                        .addComponent(btnEliminar))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void btnInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoActionPerformed

        
        switch(this.panelAlimentos.getSelectedIndex()){
            case 0://Platos
                Plato plato = ((ModeloTablaPlatos)this.tablaPlatos.getModel()).obtenerPlato(
                                this.tablaPlatos.getSelectedColumn(), this.tablaPlatos.getSelectedRow());
                this.fap.vistaProducto(this, plato);
                break;
            case 1://Bebidas
                Bebida bebida = ((ModeloTablaBebidas)this.tablaBebidas.getModel()).obtenerBebida(
                                this.tablaBebidas.getSelectedColumn(), this.tablaBebidas.getSelectedRow());
                this.fap.vistaProducto(this, bebida);
                break;
        }
        
    }//GEN-LAST:event_btnInfoActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        ModeloTablaBebidas mtb = (ModeloTablaBebidas) this.tablaBebidas.getModel();
        ModeloTablaPlatos mtp = (ModeloTablaPlatos) this.tablaPlatos.getModel();
        ArrayList<Bebida> bebidas;
        ArrayList<Plato> platos;
        platos = this.fap.buscarPlatos(this.txtBuscar.getText());
        bebidas = this.fap.buscarBebidas(this.txtBuscar.getText());
        mtb.setFilas(bebidas);
        mtp.setFilas(platos);
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        String aux = this.listPedido.getSelectedValue();
        boolean plat = false;
        for(Plato p : mesa.getPlatos()){
            if(p.getNombre().toLowerCase().equals(aux.toLowerCase()))
                plat = true;
        }
        if(plat){
            Plato plato = null;
            for(Plato p : mesa.getPlatos()){
                if(p.getNombre().toLowerCase().equals(aux.toLowerCase()))
                    plato = p;
            }
            fap.eliminarPlatoMesa(plato, this.mesa);
        }
        else{
            Bebida bebida = null;
            for(Bebida b : mesa.getBebidas()){
                if(b.getNombre().toLowerCase().equals(aux.toLowerCase()))
                    bebida = b;
            }
            fap.eliminarBebidaMesa(bebida, this.mesa);
        }
        this.actualizarModelo();
        
    }//GEN-LAST:event_btnEliminarActionPerformed
    
    
    private void btnAnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnadirActionPerformed
         ModeloTablaPlatos mtp = (ModeloTablaPlatos) this.tablaPlatos.getModel();
         ModeloTablaBebidas mtb = (ModeloTablaBebidas) this.tablaBebidas.getModel();
        if(this.tablaPlatos.isShowing() && this.tablaPlatos.getSelectedRow()>=0){
           mtp = (ModeloTablaPlatos) this.tablaPlatos.getModel();
           Plato p = mtp.obtenerPlato(this.tablaPlatos.getSelectedColumn(),this.tablaPlatos.getSelectedRow()); 
           Mesa m = this.mesa;
           fap.anadirPlatoMesa(p, m);
           p.setServicio(this.fap.obtenerServicioPlato(p));
        }
        
        if(this.tablaBebidas.isShowing() && this.tablaBebidas.getSelectedRow()>=0){
            mtb = (ModeloTablaBebidas) this.tablaBebidas.getModel();
            Bebida b =mtb.obtenerBebida(this.tablaBebidas.getSelectedColumn(), this.tablaBebidas.getSelectedRow()); 
            Mesa m = this.mesa;
            fap.anadirBebidaMesa(b, m);
            b.setServicio(this.fap.obtenerServicioBebida(b));
        }
        this.actualizarModelo();
    }//GEN-LAST:event_btnAnadirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnadir;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnInfo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JList<String> listPedido;
    private javax.swing.JTabbedPane panelAlimentos;
    private javax.swing.JTable tablaBebidas;
    private javax.swing.JTable tablaPlatos;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
