/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import restaurante.Cliente;
import restaurante.FachadaAplicacion;
import restaurante.Factura;
import restaurante.Mesa;

/**
 *
 * @author alumnogreibd
 */
public class VNuevaFactura extends javax.swing.JDialog {
    private FachadaAplicacion fap;
    private VCamarero vcam;
    private int mesa;
    private int venta;
    private float precio;

    /**
     * Creates new form VNuevaFactura
     */
    public VNuevaFactura(java.awt.Dialog parent, boolean modal,FachadaAplicacion fap, int mesa, int venta, float precio) {
        super(parent,modal);
        initComponents();
        this.fap = fap;
        this.mesa = mesa;
        this.venta = venta;
        this.precio = precio;
        
        this.txtNombreCliente.setEditable(true);
        this.txtApellidosCliente.setEditable(true);
        this.txtDni.setEditable(true);
        this.txtDireccion.setEditable(true);
        this.txtEmail.setEditable(true);
        this.Aviso.setVisible(false);
        this.Aviso1.setVisible(false);
        this.txtIdFactura.setText(String.valueOf(this.fap.obtenerIdFactura()));
        this.txtFecha.setText(this.fap.obtenerFechaActual());
        this.txtMesa.setText(String.valueOf(this.mesa));
        this.txtTotal.setText(String.valueOf(precio));
        this.txtIva.setText(String.format("%.2f",(precio / 1.21) * 0.21));
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField4 = new javax.swing.JTextField();
        btnGuardarNewFactura = new javax.swing.JButton();
        btnSalirNewFactura = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtApellidosCliente = new javax.swing.JTextField();
        txtDni = new javax.swing.JTextField();
        txtNombreCliente = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtIdFactura = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        txtMesa = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        txtIva = new javax.swing.JTextField();
        btnClienteNuevo = new javax.swing.JButton();
        btnClienteExistente = new javax.swing.JButton();
        Aviso = new javax.swing.JLabel();
        Aviso1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGuardarNewFactura.setText("Guardar");
        btnGuardarNewFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarNewFacturaActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardarNewFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 160, -1, -1));

        btnSalirNewFactura.setText("Salir");
        btnSalirNewFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirNewFacturaActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalirNewFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 300, -1, -1));

        jLabel6.setText("Datos Cliente");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        jLabel7.setText("Datos Factura");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, -1, -1));

        jLabel8.setText("Nombre:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel9.setText("DNI:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        jLabel10.setText("Direccion:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        jLabel11.setText("E-mail:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        jLabel12.setText("Apellidos:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        txtApellidosCliente.setText("Diaz Costas");
        getContentPane().add(txtApellidosCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, -1));

        txtDni.setText("69548624K");
        getContentPane().add(txtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, -1));

        txtNombreCliente.setText("Pepe");
        getContentPane().add(txtNombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, -1, -1));

        txtEmail.setText("sdfhsdhsdfghsdgh");
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, -1, -1));

        txtDireccion.setText("asdgasfgsdfgdsg");
        getContentPane().add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, -1, -1));

        jLabel13.setText("Mesa:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 180, -1, -1));
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 56, -1, -1));

        jLabel15.setText("ID Factura:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 130, -1, -1));

        jLabel16.setText("Fecha:");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 230, -1, -1));

        jLabel17.setText("IVA (21%):");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 340, -1, -1));

        jLabel19.setText("Total:");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 280, -1, -1));

        txtIdFactura.setEditable(false);
        txtIdFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdFacturaActionPerformed(evt);
            }
        });
        getContentPane().add(txtIdFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 130, -1, -1));

        txtFecha.setEditable(false);
        txtFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaActionPerformed(evt);
            }
        });
        getContentPane().add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 220, -1, -1));

        txtMesa.setEditable(false);
        txtMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMesaActionPerformed(evt);
            }
        });
        getContentPane().add(txtMesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 180, -1, -1));

        txtTotal.setEditable(false);
        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });
        getContentPane().add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 280, -1, -1));

        txtIva.setEditable(false);
        getContentPane().add(txtIva, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 340, -1, -1));

        btnClienteNuevo.setText("Nuevo");
        btnClienteNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btnClienteNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        btnClienteExistente.setText("Existente");
        btnClienteExistente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteExistenteActionPerformed(evt);
            }
        });
        getContentPane().add(btnClienteExistente, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        Aviso.setForeground(new java.awt.Color(255, 0, 0));
        Aviso.setText("El cliente ya existe");
        getContentPane().add(Aviso, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 40, -1, -1));

        Aviso1.setForeground(new java.awt.Color(255, 0, 0));
        Aviso1.setText("El cliente no existe");
        getContentPane().add(Aviso1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdFacturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdFacturaActionPerformed

    private void txtFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        
    }//GEN-LAST:event_txtTotalActionPerformed

    private void btnGuardarNewFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarNewFacturaActionPerformed
        Factura fact = new Factura(0,this.venta, this.txtDni.getText(), this.fap.obtenerFechaActual(), 
                                    this.precio, this.mesa);
        String[] apellidos;
        apellidos = this.txtApellidosCliente.getText().split(" ");
        Cliente cli = new Cliente(this.txtDni.getText(), this.txtNombreCliente.getText(), 
                                    apellidos[0], apellidos[1], 
                                    this.txtEmail.getText(), this.txtDireccion.getText());
        this.fap.anadirCliente(cli);
        this.fap.anadirFactura(fact);
        /*if(this.txtNombreCliente.isEditable() == true){
        Factura fact = new Factura(this.venta, this.txtDni.getText(), this.fap.obtenerFechaActual(), 
                                    this.precio, this.mesa);
        String[] apellidos;
        apellidos = this.txtApellidosCliente.getText().split(" ");
        Cliente cli = new Cliente(this.txtDni.getText(), this.txtNombreCliente.getText(), 
                                    apellidos[0], apellidos[1], 
                                    this.txtEmail.getText(), this.txtDireccion.getText());
            
        if(fap.obtenerCliente(this.txtDni.getText())!= null){
                this.Aviso.setVisible(true);
            }
            else{
                this.fap.anadirFactura(fact);
                this.fap.anadirCliente(cli);
            }
        }
        else{
            Factura fact = new Factura(this.venta, this.txtDni.getText(), this.fap.obtenerFechaActual(), 
                                    this.fap.precioMesa(this.fap.obtenerMesa(mesa)), this.mesa);
            
            if(fap.obtenerCliente(this.txtDni.getText())== null){
                this.Aviso1.setVisible(true);
            }
            else{
                this.fap.anadirFactura(fact);
            }
        }*/
        this.setVisible(false);
    }//GEN-LAST:event_btnGuardarNewFacturaActionPerformed

    private void txtMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMesaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMesaActionPerformed

    private void btnClienteNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteNuevoActionPerformed
        // TODO add your handling code here:
        this.txtNombreCliente.setEditable(true);
        this.txtApellidosCliente.setEditable(true);
        this.txtDni.setEditable(true);
        this.txtDireccion.setEditable(true);
        this.txtEmail.setEditable(true);
    }//GEN-LAST:event_btnClienteNuevoActionPerformed

    private void btnClienteExistenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteExistenteActionPerformed
        // TODO add your handling code here:
        this.txtNombreCliente.setEditable(false);
        this.txtNombreCliente.setText("");
        this.txtApellidosCliente.setEditable(false);
        this.txtApellidosCliente.setText("");
        this.txtDni.setEditable(true);
        this.txtDni.setText("");
        this.txtDireccion.setEditable(false);
        this.txtDireccion.setText("");
        this.txtEmail.setEditable(false);
        this.txtEmail.setText("");
    }//GEN-LAST:event_btnClienteExistenteActionPerformed

    private void txtNombreClienteActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
        this.Aviso.setVisible(false);
    }                                                

    private void txtDniActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        this.Aviso.setVisible(false);
        this.Aviso1.setVisible(false);
    }                                      

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void btnSalirNewFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirNewFacturaActionPerformed
        // TODO add your handling code her:
        this.setVisible(false);
        
    }//GEN-LAST:event_btnSalirNewFacturaActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Aviso;
    private javax.swing.JLabel Aviso1;
    private javax.swing.JButton btnClienteExistente;
    private javax.swing.JButton btnClienteNuevo;
    private javax.swing.JButton btnGuardarNewFactura;
    private javax.swing.JButton btnSalirNewFactura;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField txtApellidosCliente;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtIdFactura;
    private javax.swing.JTextField txtIva;
    private javax.swing.JTextField txtMesa;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
