/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import restaurante.Bebida;
import restaurante.FachadaAplicacion;
import restaurante.Mesa;
import restaurante.Plato;

/**
 *
 * @author davidmacar
 */
public class VProducto extends javax.swing.JDialog {

    FachadaAplicacion fap;
    javax.swing.JDialog ventana;
    Plato plato;
    Bebida bebida;
    
    public VProducto(java.awt.Dialog parent, boolean modal, FachadaAplicacion fap, Object alimento) {
        super(parent, modal);
        this.fap = fap;
        switch(parent.getClass().getName().toLowerCase()){
            case "vmenu":
                this.ventana = (VMenu) parent;
                break;
        }
        switch(alimento.getClass().getName().toLowerCase()){
            case "restaurante.plato":
                this.plato = (Plato) alimento;
                this.bebida = null;
                break;
            case "restaurante.bebida":
                this.bebida = (Bebida) alimento;
                this.plato = null;
                break;
                
        }
        initComponents();
        actualizarNombre();
        actualizarDescripcion();
    }
    
    
    public void actualizarNombre(){
        if(plato != null)
            this.txtNombre.setText(this.plato.getNombre());
        else
            this.txtNombre.setText(this.bebida.getNombre());
            
    }
   
    public void actualizarDescripcion(){
        if(plato != null)
            this.txtDescripcion.setText(this.plato.getDescripcion());
        else
            this.txtDescripcion.setText(this.bebida.getNombre());
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNombre = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();

        txtNombre.setText("Nombre producto");

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        jScrollPane1.setViewportView(txtDescripcion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(145, Short.MAX_VALUE)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115))
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JLabel txtNombre;
    // End of variables declaration//GEN-END:variables
}
